git:
  parseEmoji: false
gui:
  nerdFontsVersion: "3"
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with git-cz"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true