import = ['C:\Users\JonathanDent\AppData/Roaming/alacritty/themes/catppuccin-mocha.toml']

[bell]
animation = "EaseOutExpo"
color = "#ffffff"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[shell]
program = "pwsh"
#working_directory = 'x:\'

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = false
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 35

[window.padding]
x = 0
y = 0

[window.position]
x = 200
y = 200
